# Generated by Django 4.2.7 on 2024-05-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('guardID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('guardName', models.TextField(max_length=255)),
                ('guardPhoneno', models.CharField(max_length=20)),
                ('guardPassword', models.CharField(max_length=10)),
            ],
        ),
    ]
