# Generated by Django 4.2.7 on 2024-05-29 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residentialvisitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('resID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('resName', models.TextField(max_length=255)),
                ('resIC', models.CharField(max_length=14)),
                ('resGender', models.TextField(max_length=6)),
                ('resRace', models.TextField(max_length=20)),
                ('resPhoneno', models.CharField(max_length=20)),
                ('houseNo', models.CharField(max_length=6)),
                ('street', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('resPassword', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visName', models.TextField(max_length=255)),
                ('visIC', models.CharField(max_length=14)),
                ('visPhoneno', models.CharField(max_length=20)),
                ('platNo', models.CharField(max_length=20)),
                ('houseNo', models.CharField(max_length=6)),
                ('street', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('purpose', models.TextField(max_length=255)),
                ('date', models.DateField()),
                ('timeIn', models.TimeField()),
                ('timeOut', models.TimeField()),
                ('duration', models.CharField(max_length=5)),
                ('status', models.TextField(default='Registered', max_length=10)),
                ('resID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentialvisitor.resident')),
            ],
        ),
        migrations.CreateModel(
            name='ReportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueName', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.TextField(default='Submitted', max_length=10)),
                ('guardID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentialvisitor.guard')),
                ('resID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentialvisitor.resident')),
            ],
        ),
        migrations.CreateModel(
            name='ReportGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardName', models.TextField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.TextField(default='Submitted', max_length=10)),
                ('resID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentialvisitor.resident')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.TextField(max_length=255)),
                ('houseNo', models.CharField(max_length=6)),
                ('street', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.CharField(max_length=5)),
                ('numOfVisitor', models.IntegerField()),
                ('message', models.TextField(max_length=255, null=True)),
                ('resID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentialvisitor.resident')),
            ],
        ),
    ]
