# Generated by Django 4.2.7 on 2024-05-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentialvisitor', '0002_resident_visitor_reportissue_reportguard_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='timeIn',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='timeOut',
            field=models.TimeField(null=True),
        ),
    ]
