# Generated by Django 4.2.7 on 2024-05-30 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residentialvisitor', '0003_alter_visitor_timein_alter_visitor_timeout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='platNo',
            new_name='plateNo',
        ),
    ]
