# Generated by Django 4.2.7 on 2024-06-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentialvisitor', '0005_reportguard_guardid_visitor_guardid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('adminName', models.TextField(max_length=255)),
                ('adminIC', models.CharField(max_length=14)),
                ('adminGender', models.TextField(max_length=6)),
                ('adminRace', models.TextField(max_length=20)),
                ('adminPhoneno', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=30)),
                ('adminPassword', models.CharField(max_length=10)),
            ],
        ),
    ]
