# Generated by Django 4.2.7 on 2024-06-10 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('residentialvisitor', '0006_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='adminID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residentialvisitor.admin'),
        ),
        migrations.AddField(
            model_name='reportguard',
            name='adminID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residentialvisitor.admin'),
        ),
        migrations.AddField(
            model_name='reportissue',
            name='adminID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residentialvisitor.admin'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='adminID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residentialvisitor.admin'),
        ),
        migrations.AlterField(
            model_name='event',
            name='resID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residentialvisitor.resident'),
        ),
        migrations.AlterField(
            model_name='reportguard',
            name='resID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='residentialvisitor.resident'),
        ),
    ]
