# Generated by Django 4.2.7 on 2024-06-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentialvisitor', '0007_event_adminid_reportguard_adminid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='guardPost',
            field=models.CharField(default='Post 1', max_length=6),
        ),
        migrations.AddField(
            model_name='guard',
            name='guardShift',
            field=models.CharField(default='Day Shift', max_length=15),
        ),
    ]
