# Generated by Django 4.2.7 on 2024-06-16 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residentialvisitor', '0009_guard_numofreports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guard',
            name='numOfReports',
        ),
    ]
