# Generated by Django 4.2.7 on 2024-06-19 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residentialvisitor', '0010_remove_guard_numofreports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='address',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='adminGender',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='adminRace',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='position',
        ),
    ]
