# Generated by Django 4.2.7 on 2024-06-20 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentialvisitor', '0011_remove_admin_address_remove_admin_admingender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportissue',
            name='measuresTaken',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
