# Generated by Django 4.2.7 on 2024-06-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentialvisitor', '0012_reportissue_measurestaken'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportguard',
            name='measuresTaken',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
